### ISSUE TITLE
Using `why-did-you-update` points to small avoidable re-renders

### ISSUE THREAD

**Issue by fernandofleury** [twobin/react-lazyload#112]
Greetings! I was searching for a lazyload lib for react, and this project works wonderfully :)

I've been using [why-did-you-update](https://github.com/garbles/why-did-you-update) along with constant performance checks on my applications, and the library pointed out a few points of improvement of the component lifecycle:

![image](https://user-images.githubusercontent.com/2780941/28526210-217ec7bc-7087-11e7-92af-1d23772b66cf.png)

Is this on the roadmap on the component? Should I work on a PR to fix it? Thanks!

**Comment by jasonslyvia** [comment]
LazyLoad maintains a local state called `visible` which is neither props nor state, that's why you get such output.
I believe there is a way to improve this though.

**Comment by fernandofleury** [comment]
Hi @jasonslyvia sorry for the delay. Maybe I can help with it? Which part of the code should I look into?

**Comment by fernandofleury** [comment]
@jasonslyvia I see this part of the code: 

```js
// index.js line 258
  shouldComponentUpdate() {
    return this.visible;
  }
```
so maybe one way to approach this is having the previous visible and using that to verify the shouldComponentUpdate? something like:

```js
// index.js line 125
component.previousVisibility = component.visible; // not sure about the naming, just an idea
```

and then change the shouldComponentUpdate to something like:
```js
  shouldComponentUpdate() {
    return this.visible && (this.previousVisibility !== this.visible);
  }
```

the only thing I'm not so sure is about the strategy of the update there. should we always update if visible and different from the previous state, or should if be update is it is not visible anymore as well?

I can work on a PR for this with no problem, I just want to make sure I'm in the right direction.

Thanks!

**Comment by jasonslyvia** [comment]
@fernandofleury Excellent work! I really anticipate this PR.

**Comment by lauterry** [comment]
Shouldn't this issue be closed ?
