### ISSUE TITLE
Delay Prop for placeholder to disappear.

### ISSUE THREAD

**Issue by mthines** [twobin/react-lazyload#134]
## Hey!

Is it possible to add a delay before the placeholder gets removed from the dom?
Then I could add a CSS animation so that the placeholder gets animated out when the image is ready.

Maybe there's a setting I can't find.

Thanks a lot! 💪

**Comment by mads-thines** [comment]
Also, I'm experiencing the lazyload not replacing the placeholder before you've stopped scrolling.

**Comment by jasonslyvia** [comment]
The default delay function for `react-lazyload` is debounce so you may not experience a lazy load effect before scroll stops, you can switch to `throttle` to change this behavior.

Another delay props sounds achievable, I'll add this to feature list and find some time to implement.

**Comment by mads-thines** [comment]
@jasonslyvia If you need help with the specs needed in order to do a great animation you can write me and I'll be happy to contribute. Ideal there should be added temporary classes that you can do CSS' animations from :)

**Comment by mads-thines** [comment]
@jasonslyvia But as illustrated in the gif below, even though throttle and debounce is set to false, it still doesn't render before I stop scrolling.

![no render while scrolling](https://user-images.githubusercontent.com/16097850/32835192-7e7e8f88-ca05-11e7-9e0d-029582fae851.gif)

**Comment by mads-thines** [comment]
@jasonslyvia Alright, I got it working. 
Here's the settings that did the trick for me.

```
debounce: 0,
throttle: 100,
```

I hope it helps if somebody else runs into the issue

**Comment by jasonslyvia** [comment]
@mads-thines speaking of animation, have you checked [this demo](https://jasonslyvia.github.io/react-lazyload/examples/#/fadein?_k=zav6si)? is that what you expected?

**Comment by mads-thines** [comment]
@jasonslyvia The animation I'm talking about is the one you can see in the end of the Gif I send.
The transition from the placeholder to the real photo, and then animation the filter: blur(); so the image blurs in :)

**Comment by flikQ** [comment]
@jasonslyvia @mthines did this delay prop ever get added? I am finding that there is a noticeable gap between when the Placeholder vanishes and the actual item appears. 

My use case is I have a small video that is loading in, but a static image of that video is the placeholder, so the expected behaviour is that you it should visually just start playing seamlessly.

**Comment by mthines** [comment]
I ended up writing the whole lazy thing my self, which took less time actually.
