### ISSUE TITLE
LazyLoad is not working when the style of container <div> is {display:none}

### ISSUE THREAD

**Issue by Rui-Sun** [twobin/react-lazyload#152]
I found a serious problem when I updated react-layload from 2.2.7 to 2.3.0. The JSX code in my project is like: 
```html
<div style={{display: 'none'}}>
    <LazyLoad height={'100%'}>
        <StyleBox/>
    </LazyLoad>
</div>
```
It works well with 2.2.7. However, the component StyleBox dose not construct with 2.3.0. Therefore the component dose not show when the style of container changes from {display:none} to {display:block}.

The element in <LazyLoad> is always:
```html
<div style={height: 100%} class="lazyload-placeholder"></div>
```

the version of react is 15.6.2

**Comment by jasonslyvia** [comment]
I don't believe `2.3.0` made any change regarding this behavior

**Comment by Rui-Sun** [comment]
I wrote a demo:
```JSX
import React, { Component } from 'react';
import LazyLoad from 'react-lazyload';

class App extends Component {
  constructor() {
    super();
    this.state = {
      show: false,
    }
  }

  click() {
    this.setState({
      show: !this.state.show,
    });
  }

  render() {
    return (
      <div>
        <button className="button" onClick={this.click.bind(this)}>click</button>
        <div id="container" style={{ display: this.state.show ? 'block' : 'none' }}>
          <LazyLoad height={'100%'}>
            <div>hello world!</div>
          </LazyLoad>
        </div>
      </div>
    );
  }
}

export default App;
```

In 2.3.0, it works well when init state is {show: true}, but it dose not work when init state is {show: false}. It goes well all the time if the version changes to 2.2.7.

**Comment by hzyhbk** [comment]
LazyLoad is not working when the style of container <div> is {height:'100vh', overflow: 'scroll'}
![ianb mc1kr xr60 f8v2 v](https://user-images.githubusercontent.com/42671099/52758405-154fbc80-3043-11e9-97b3-71256d335517.png)

**Comment by ameerthehacker** [comment]
@Rui-Sun can you please share a jsbin minimal example

**Comment by hzyhbk** [comment]
> LazyLoad is not working when the style of container
> 
> is {height:'100vh', overflow: 'scroll'}
> ![ianb mc1kr xr60 f8v2 v](https://user-images.githubusercontent.com/42671099/52758405-154fbc80-3043-11e9-97b3-71256d335517.png)


Oh I see,because I didn't set the props overflow to true,after set the props overflow={true},it works

**Comment by ameerthehacker** [comment]
@Rui-Sun and @hzyhbk i think this issue is resolved. I will close the issue for now, please feel free to reopen it if you still face any problems.
