### ISSUE TITLE
[react-lazyload] Please add `height` props to <LazyLoad> for better performance.

### ISSUE THREAD

**Issue by cainvommars** [twobin/react-lazyload#155]
Could anyone please explain why this is impacting performance?

My usage:
I'm always rendering a placeholder that has the exact size of the element that will created by lazy load. The browser will not push other content around.

**Comment by jasonslyvia** [comment]
in your case you don't have to specify `height` then

**Comment by cainvommars** [comment]
Thats what i thought. Can I somehow suppress the warning then? :)

**Comment by northern** [comment]
If the `height` isn't a requirement and entirely optional then it would be better not to output the warning since its just creating unnecessary logging. +1 for removal.
