### ISSUE TITLE
findDOMNode was called on an unmounted component.

### ISSUE THREAD

**Issue by wsdo** [twobin/react-lazyload#186]
config ：
 new webpack.DefinePlugin({
       "process.env.NODE_ENV": JSON.stringify("production")
}）

error：
![_dfc21727-8466-4f9f-b172-7b65723ce94a](https://user-images.githubusercontent.com/9738969/41909639-275b0a18-797a-11e8-96d9-f98c4ddac088.png)

**Comment by khurrumqureshi** [comment]
any update on this?

**Comment by NNSTH** [comment]
Any update? This issue makes a lot of noise on our production monitoring system!

**Comment by NNSTH** [comment]
Thank you very much @ameerthehacker , I appreciate your quick response.
When will you make a new release so I can take it official?
