### ISSUE TITLE
Should upgrade to Babel 7?

### ISSUE THREAD

**Issue by iAziz786** [twobin/react-lazyload#207]
Since version 7 of the Babel is out, should we consider upgrading this project to it?

If the maintainer is okay with this I would like to work on this upgrade.

**Comment by iAziz786** [comment]
Okay, I'll start working on the upgrade.

Indeed I don't want to make any breaking changes, that is why can I get some help on testing?

**Comment by jasonslyvia** [comment]
I guess bottom line is all tests get passed

**Comment by iAziz786** [comment]
I have started to implement the changes. Due to upgradation, I had to make some changes to the `karma.config.js` file.

I hope that's fine?

**Comment by jasonslyvia** [comment]
yeah, that's fine
