### ISSUE TITLE
findDOMNode will be deprecated

### ISSUE THREAD

**Issue by dsempel** [twobin/react-lazyload#209]
Starting from React 16.6 it is deprecated in StrictMode and it will be deprecated from React in the future. [Here](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage) is some more information about this.

The docs state the following:
> Normally you don’t need this because you can attach a ref directly to a DOM node.

The warning in StrictMode:
> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of VisibilitySensor which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

**Comment by jasonslyvia** [comment]
Maybe we should implement some ref pass through technique to bypass this issue? The DOM node should be accessed anyway though.

**Comment by sjsn** [comment]
@ameerthehacker Any news on when #242 will make it into an npm release? The build files in 2.6.2 still have the `findDOMNode` code.

**Comment by pelotom** [comment]
*bump*

It would be great if we could get a release with this fix!

**Comment by rafaelcamaram** [comment]
I do believe that it's an important fix that needs to be accomplished. These warn are being very annoying.

**Comment by ameerthehacker** [comment]
@rafaelcamaram I totally understand it, the fix has been in beta for few weeks now already and I will release it tomorrow
