### ISSUE TITLE
why component and image lazyload is  fail ???

### ISSUE THREAD

**Issue by JinJieTan** [twobin/react-lazyload#236]
import { lazyload } from 'react-lazyload' 
```
<div className="KingkongModule">
                {KingkongModule.map((item, index) => {
                    return <div onClick={this.handleClick(item)} className="kingkong-item" key={index}>
                            <img src={item.picUrl} alt="" />
                        <span>{item.text}</span></div>
                })}
</div>
            ```

export default lazyload({
    height: 200,  //only this option is ok  , but forever state is   class="lazyload-placeholder"  ,component is   Unmount! 
    offset: 150  
})(
    withRouter(connect(
        (state) => ({ KingkongModule: state.KingKong }),
        (dispatch) => ({
            reqKingKongModule() {
                const action = AsyncKingKongModule();
                dispatch(action)
            },

        })
    )(App))
)

**Comment by liplylie** [comment]
if the class lazyload-placeholder isn't going away when the element is in viewport, it is possible that your lazy load component is not detecting the window scroll event.

Try using `scrollContainer` and set the value to '.KingkongModule'
