### ISSUE TITLE
Does the library support horizontal lazy load out of the box ? 

### ISSUE THREAD

**Issue by Sara2009** [twobin/react-lazyload#239]
In the readme.md the props `offset` says it supports horizontal lazyload and we can set it as an array. But in the source code, there is no method to judge the horizontal scroll visible? Is there is something wrong or am I missing something?

**Comment by chrisdopuch** [comment]
I'm building a horizontally scrollable image gallery, and I'm finding that the lazy loading does not work (all images get loaded at once, even ones that are fully off the screen). I will try using the `preventLoading` prop, but it would be great if this "just worked" out of the box.

**Comment by chrisdopuch** [comment]
Looks like this issue is still open, so that's officially a "no" on horizontal scrolling:
https://github.com/twobin/react-lazyload/issues/56

This can probably be closed as duplicate @Sara2009 , I hope that it gets implemented soon! 🤞

**Comment by ameerthehacker** [comment]
@chrisdopuch @Sara2009 #231 PR added it and it is already published

**Comment by chrisdopuch** [comment]
Amazing! Thanks @ameerthehacker , I guess the other ticket should get closed then. So happy to hear this! ❤️

**Comment by ameerthehacker** [comment]
Thanks, @chrisdopuch I have closed the ticket #56

**Comment by tomellwood** [comment]
I'm having a similar issue @chrisdopuch opened with, all images loading at once on scroll. Is there a working example of how horizontal scrolling lazy-loading works? @ameerthehacker

**Comment by ttmthanh** [comment]
I set offset but seem it does not work with horizontal list :'(
