### ISSUE TITLE
latest NPM build not including the latest code?

### ISSUE THREAD

**Issue by Ligerx** [twobin/react-lazyload#253]
Hey, I picked out this project specifically because it has the `preventLoading` prop.
But after I installed the latest version `"react-lazyload": "^2.6.2",` I noticed that preventLoading didn't do anything.

According to NPM, 2.6.2 was published 2 months ago, but I noticed that you only bumped the version in a commit 9 days ago. fc71244ab7dd5e00ce23d90660f9b1a8a9c0c848

It seems like the code living in NPM is not the most up to date code for some reason.

Probably related to issue https://github.com/twobin/react-lazyload/issues/250

Thanks!

**Comment by ameerthehacker** [comment]
Hey @Ligerx I did not commit the version after bumping and publishing the npm package sorry my bad. I'm planning to add semantic release to prevent this in the future from happening.

**Comment by robinvw1** [comment]
@ameerthehacker Can you re-open this issue until you have published the latest and greatest from git to npm? Other people will encounter this issue as well (like me) and keeping it open makes it more searchable.

Until npm is not in sync with `master` and you really need the `preventLoading` prop (like me), you can install the package from git:
```
npm install --save twobin/react-lazyload
```

I have also opened a PR to update the TypeScript definitions:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39002

**Comment by matthewkwong2** [comment]
@ameerthehacker You may want to consider pinning/re-opening this issue until the latest version has been published to NPM. I have literally spent over an hour to realize why my `preventLoading` prop does nothing.
