### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by umarmw** [twobin/react-lazyload#274]
Does anyone knows how to write it in Typescript?

**Comment by hatton** [comment]
sure just `yarn add @types/react-lazyload`

**Comment by YevKo** [comment]
And what's next? Used an example from the Readme
`import { lazyload } from 'react-lazyload';

@lazyload({
  height: 200,
  once: true,
  offset: 100
})`

 and got this error:

`TS1146: Declaration expected.`

**Comment by RicoLiu** [comment]
```shell
 npm install --save @types/react-lazyload    
```

**Comment by ameerthehacker** [comment]
Closing this issue as you can use definitely type, feel free to reopen if there are any other issues.
