### ISSUE TITLE
forceVisible() not working

### ISSUE THREAD

**Issue by Rockatweb** [twobin/react-lazyload#291]
Hi,
i updated the lib to the current version because i need the forceVisible(); function.
But this function does not work and if i look in the dependency in my node_modules folder this function cannot be found. It seem that the lib folder wasn't updated.

Could you please fix this?

**Comment by ameerthehacker** [comment]
Sure will cut a release soon

**Comment by ameerthehacker** [comment]
v2.6.6 has been released with this, do check and let me know.

feel free to reopen the issue if you face any issues.

Thanks for raising this!

**Comment by Rockatweb** [comment]
works very well. thanks for the update
