### ISSUE TITLE
High CPU usage when using placeholder

### ISSUE THREAD

**Issue by Adrien-D** [twobin/react-lazyload#299]
With the last version 2.6.7, my CPU is now around 40% when I'm using the placeholder props (with around 20 lazyload components).

Looks like something is looping no matter what :
![Issue](https://user-images.githubusercontent.com/4726647/78573123-a2963780-7828-11ea-94ca-532e9f7f94ac.png)

**Comment by ameerthehacker** [comment]
> With the last version 2.6.7, my CPU is now around 40% when I'm using the placeholder props (with around 20 lazyload components).
> 
> Looks like something is looping no matter what :
> ![Issue](https://user-images.githubusercontent.com/4726647/78573123-a2963780-7828-11ea-94ca-532e9f7f94ac.png)
> 

Hi nothing has actually changed in 2.6.7, are you still facing the issue
