### ISSUE TITLE
react-lazyload don't work with display:flex and height

### ISSUE THREAD

**Issue by anna-tsukanova** [twobin/react-lazyload#301]
With a situation like 
`div>ul>li` where `li` wrap by `LazyLoad` component, `ul` has `display: flex;  flex-direction: column;` and fixed `height` property and div has `overflow: auto` and fixed `height`. But it doesn't work correctly. Only when I changed in `ul` component height to flex-basis it started work.

Maybe with a small piece of code will be better to understand the situation 
```
div.Jokes {
  height: 55vh;
  overflow: auto;
  position: relative;
}

ul.Jokes__list {
  display: flex;
  flex-direction: column;
  height: 45vh; (not work - only with flex-basis)
  overflow: visible;
}

li.Jokes__item {
  height: auto;
}
```

**Comment by srmaharjan** [comment]
I think you have to set [https://github.com/twobin/react-lazyload#scrollcontainer](scrollContainer) props.

**Comment by AnnabellFlem** [comment]
@srmaharjan it works for me! Thank you!!
