### ISSUE TITLE
[WARNING] findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by rafaelcamaram** [twobin/react-lazyload#303]
I'm getting the following warning regarding the `react-lazyload`:

> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of VisibilitySensor which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

Is there any idea about when it'll be resolved? I saw that there was already an issue related to it here but it was closed in 2019.

**Comment by ameerthehacker** [comment]
@rafaelcamaram the fix is already in beta and I will release it to stable tomorrow

**Comment by rafaelcamaram** [comment]
I'm glad to know that! 🚀

Thank you for the quick answer

**Comment by rafaelcamaram** [comment]
@ameerthehacker Is it already published to NPM?

**Comment by spenceruns** [comment]
I'm having this issue as well. Is there a release date for the fix?

**Comment by ameerthehacker** [comment]
@rafaelcamaram @spenceruns Sorry could not cut a release last week,  will release it this weekend

**Comment by a20070322** [comment]
Is it already published to NPM?

**Comment by rafaelcamaram** [comment]
@ameerthehacker I'm still waiting also

**Comment by ameerthehacker** [comment]
@rafaelcamaram @a20070322 sorry for the delay, I just wanted the beta to last little longer, if no bugs turn up by end of the week I will publish and update you all

Thanks for your patience on this one

**Comment by a20070322** [comment]
Thank you for your efforts and wish you all the best in far away China。

**Comment by a20070322** [comment]
Thank you for your efforts and wish you all the best in far away China。

**Comment by rk2609** [comment]
@ameerthehacker Anu update on the fix?

**Comment by rafaelcamaram** [comment]
@ameerthehacker Any updates?

**Comment by ameerthehacker** [comment]
@rafaelcamaram @rk2609 investigating https://github.com/twobin/react-lazyload/issues/273#issuecomment-640155786

**Comment by ryardley** [comment]
This issue might mean unfortunately we might need to remove this from our codebase soon.

**Comment by ameerthehacker** [comment]
@ryardley apologise, I totally understand how important this is, will be cutting a release today to fix this for good

**Comment by ameerthehacker** [comment]
@ryardley @rafaelcamaram @rk2609 @a20070322 this has been fixed and release as verion 2.6.8 in npm, do check and let me know

**Comment by ameerthehacker** [comment]
closing this issue, feel free to reopen if there are any issues
