### ISSUE TITLE
Images not loading on iPhone

### ISSUE THREAD

**Issue by chiragbhansali** [twobin/react-lazyload#306]
I am using this library to lazy load images on my website. It works perfectly in Chrome and Firefox on both laptop and Android. However, some of the images don't load when I open the site in Safari and Chrome on iOS.  How can I fix this?

**Comment by a-ssassi-n** [comment]
I am facing the same issue. How did you solve this?

**Comment by chiragbhansali** [comment]
> I am facing the same issue. How did you solve this?

After some debugging, I found that there was some issue with the format of certain images. I fixed it by converting it to other formats using Sharp and then used `<picture>` tag to include them in the website.
