### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by petertenhoor** [twobin/react-lazyload#331]
Could you update the React version in the package.json to React 17 please 😄

**Comment by ameerthehacker** [comment]
Sure @petertenhoor a PR would be very helpful if possible.

**Comment by magnnus** [comment]
That is NOT accessible on NPM when I install this package. It will warn:

```shell
npm WARN react-lazyload@3.1.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by hinsenchan** [comment]
@ameerthehacker there's an issue with the 3.1.0 release in the Yarn registry. The change that adds React ^17.0.0 to the peer dependency list is not there after installing it.
