### ISSUE TITLE
Handle horizontal axis

### ISSUE THREAD

**Issue by NeXTs** [twobin/react-lazyload#56]
Currently plugin observes vertical axis only.

How about horizontal one?
On my website I have huge horizontal list and I would like to apply lazyloading for items in those list too.

**Comment by jasonslyvia** [comment]
Sure, it's achievable, just wish I'd get more time to implement it :)

**Comment by Harryandrew** [comment]
+1 on this! this would be amazing

**Comment by jonathanobino** [comment]
I've solved this in my version of react [lazy loading components](https://github.com/jonathanobino/react-lazy)

**Comment by vaibhav-iiit** [comment]
@jasonslyvia I have a feature which requires horizontal scroll lazy load. Is there any plan of releasing this in near future? If no, is there any way of achieving it?

**Comment by zengxiaoluan** [comment]
支持图片横向懒加载了吗？

**Comment by Simonboeuf1** [comment]
any news on this ? This package is super easy to use, and it would just be great to handle horizontal scroll

**Comment by ameerthehacker** [comment]
#231 PR added it and it is already published.
